import { StyleSheet } from 'react-native';
import { BorderRadius, BorderWidth, Spacing, Theme } from '@/constants/theme';
import { withAlpha } from '@/utils/colors';
import { rf, rs } from '@/utils/responsive';

export const createStyles = (theme: Theme) => StyleSheet.create({
  keyboardRoot: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: theme.backgroundRoot,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm + 2,
    backgroundColor: theme.backgroundDefault,
    borderBottomWidth: BorderWidth.normal,
    borderBottomColor: theme.border,
  },
  backButton: {
    width: rs(44),
    height: rs(44),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.sm,
  },
  title: {
    flex: 1,
    fontSize: rf(20),
    fontWeight: '700',
    color: theme.textPrimary,
    letterSpacing: -0.5,
  },
  listContent: {
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  ruleInfoCard: {
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: theme.backgroundDefault,
    borderWidth: BorderWidth.thick,
    borderColor: theme.border,
  },
  ruleName: {
    fontSize: rf(18),
    fontWeight: '800',
    color: theme.textPrimary,
    marginBottom: 4,
  },
  ruleDescription: {
    fontSize: rf(13),
    lineHeight: rf(19),
    color: theme.textMuted,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Spacing.sm,
  },
  summaryText: {
    fontSize: rf(12),
    fontWeight: '600',
    color: theme.success,
  },
  summaryDot: {
    marginHorizontal: Spacing.xs,
    color: theme.textMuted,
  },
  tipCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: withAlpha(theme.success, 0.08),
    borderWidth: BorderWidth.normal,
    borderColor: withAlpha(theme.success, 0.22),
  },
  tipIcon: {
    width: rs(34),
    height: rs(34),
    borderRadius: BorderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: withAlpha(theme.success, 0.12),
  },
  tipText: {
    flex: 1,
    fontSize: rf(13),
    lineHeight: rf(19),
    color: theme.textSecondary,
  },
  fieldCard: {
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    backgroundColor: theme.backgroundDefault,
    borderWidth: BorderWidth.thick,
    borderColor: theme.border,
  },
  fieldCardConfigured: {
    backgroundColor: withAlpha(theme.success, 0.08),
    borderColor: withAlpha(theme.success, 0.3),
  },
  fieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  fieldIndex: {
    width: rs(30),
    height: rs(30),
    borderRadius: BorderRadius.full,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.backgroundTertiary,
    marginRight: Spacing.sm,
  },
  fieldIndexConfigured: {
    backgroundColor: theme.success,
  },
  fieldIndexText: {
    fontSize: rf(13),
    fontWeight: '800',
    color: theme.textSecondary,
  },
  fieldIndexTextConfigured: {
    color: theme.buttonPrimaryText,
  },
  fieldTitleWrap: {
    flex: 1,
  },
  fieldLabel: {
    fontSize: rf(15),
    fontWeight: '700',
    color: theme.textPrimary,
    marginBottom: 2,
  },
  fieldSubtitle: {
    fontSize: rf(11),
    color: theme.textMuted,
  },
  inputWrap: {
    minHeight: rs(46),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: theme.backgroundTertiary,
    borderWidth: BorderWidth.normal,
    borderColor: theme.border,
  },
  inputWrapConfigured: {
    backgroundColor: withAlpha(theme.success, 0.1),
    borderColor: withAlpha(theme.success, 0.34),
  },
  prefixInput: {
    flex: 1,
    fontSize: rf(15),
    color: theme.textPrimary,
    paddingVertical: Spacing.sm + 2,
  },
  clearButton: {
    marginLeft: Spacing.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
    borderRadius: BorderRadius.sm,
    backgroundColor: withAlpha(theme.success, 0.14),
  },
  clearButtonText: {
    fontSize: rf(12),
    fontWeight: '700',
    color: theme.success,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing['4xl'],
    gap: Spacing.sm,
  },
  emptyText: {
    fontSize: rf(14),
    color: theme.textMuted,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingTop: Spacing.sm,
    paddingHorizontal: Spacing.md,
    backgroundColor: theme.backgroundDefault,
    borderTopWidth: BorderWidth.normal,
    borderTopColor: theme.border,
  },
  clearAllButton: {
    flex: 1,
    minHeight: rs(48),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: BorderRadius.md,
    backgroundColor: theme.backgroundTertiary,
    borderWidth: BorderWidth.normal,
    borderColor: theme.border,
  },
  clearAllButtonText: {
    fontSize: rf(15),
    fontWeight: '700',
    color: theme.textPrimary,
  },
  saveButton: {
    flex: 1,
    minHeight: rs(48),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: BorderRadius.md,
    backgroundColor: theme.success,
  },
  saveButtonText: {
    fontSize: rf(15),
    fontWeight: '800',
    color: theme.buttonPrimaryText,
  },
});
